name: create release
on: workflow_dispatch
jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    container: jrottenberg/ffmpeg:5.0-ubuntu
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        apt update
        apt install -y --no-install-recommends clang curl pkg-config
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
    - uses: katyo/publish-crates@v1
      with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}